/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HiEveryone;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testStringRepeatJava11() {
        String repeated = "abc".repeat(3);
        assertEquals("abcabcabc", repeated);
    }

    @Test
    public void testJava21() {
        List<Integer> list = new ArrayList<>();
        list.add(1);
        list.addFirst(0);
        list.addLast(2);
        assertEquals(3, list.size());
    }
}
